package it.polimi.ingsw.enumeration;

/**
 * enumeration for the message content
 */
public enum MessageContent {
    CONNECTION, CONNECTION_RESPONSE, ADD_PLAYER,
    PASS_TURN, RESPONSE, GAME_STATE, WINNER, DISCONNECTION, PING, READY, RECONNECTION, GAME_LOAD,
    NUMBER_OF_PLAYERS, SETUP_NUMBER_OF_PLAYERS, BOARD, PLAYERS_IN_LOBBY, OBJECT_CARD_VALID, PICK_OBJECT_CARD,
    LOAD_SHELF_REQUEST, AVAILABLE_COLUMNS_RESPONSE, REORDER_LIMBO_REQUEST, DELETE_LIMBO, GAME_ENDED, LIST_GAME, JOIN_GAME, CREATE_GAME,
}
