package it.polimi.ingsw.enumeration;

public enum MessageContent {
    CONNECTION, CONNECTION_RESPONSE, ADD_PLAYER, COLOR, COLOR_RESPONSE, LOBBY_VOTE, VOTE_RESPONSE,
    BOT_SPAWN, DISCARD_POWERUP, BOT_ACTION, MOVE, MOVE_PICK, SHOOT, RELOAD, POWERUP_USAGE,
    PASS_TURN, RESPONSE, GAME_STATE, WINNER, DISCONNECTION, PING, READY, RECONNECTION, GAME_LOAD,
    NUMBER_OF_PLAYERS, SETUP_NUMBER_OF_PLAYERS, BOARD, PLAYERS_IN_LOBBY, PICK_OBJECT_CARD
}
