package it.polimi.ingsw.enumeration;

public enum MessageContent {
    CONNECTION, CONNECTION_RESPONSE, ADD_PLAYER, LOBBY_VOTE,
    PASS_TURN, RESPONSE, GAME_STATE, WINNER, DISCONNECTION, PING, READY, RECONNECTION, GAME_LOAD,
    NUMBER_OF_PLAYERS, SETUP_NUMBER_OF_PLAYERS, BOARD, PLAYERS_IN_LOBBY, OBJECT_CARD_VALID, PICK_OBJECT_CARD,
    LOAD_SHELF_REQUEST, AVAILABLE_COLUMNS_RESPONSE, REORDER_LIMBO_REQUEST,
}
